# Server configuration
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api

# Spring Data Source - MySQL (Railway)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://switchback.proxy.rlwy.net:32170/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kIzEgSUTmmOukUVGjLiyXfaBxcuVdipA}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open-in-View warning
spring.jpa.open-in-view=false

# H2 Console (Disabled as we use MySQL)
spring.h2.console.enabled=false
